"""Initial Migration

Revision ID: 08e80e7760f9
Revises: 
Create Date: 2018-05-18 07:13:15.166857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e80e7760f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecosystems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('fetch_url', sa.String(length=255), nullable=True),
    sa.Column('_backend', sa.Enum('none', 'npm', 'maven', 'pypi', 'rubygems', 'scm', 'crates', 'nuget', name='ecosystem_backend_enum'), nullable=True),
    sa.Column('test', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'test'),
    sa.UniqueConstraint('name')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecosystem_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem_id', 'name', name='ep_unique')
    )
    op.create_index(op.f('ix_packages_name'), 'packages', ['name'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('synced2graph', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'identifier', name='pv_unique')
    )
    op.create_index(op.f('ix_versions_identifier'), 'versions', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versions_identifier'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_packages_name'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('ecosystems')
    # ### end Alembic commands ###
